### ISSUE TITLE
Pod 'SOS' 1.2.3 version generates more than 200 warnings

### ISSUE THREAD

**Issue by JaviLorbada** [goinstant/pods-specs-public#1]
Hi Guys,

As you can see in the screenshot below, the version 1.2.3 of SOS generates more than 200 warnings.

<img width="1920" alt="soswarnings" src="https://cloud.githubusercontent.com/assets/1939155/11357050/b7d57fe4-929e-11e5-958b-4a6710e7e71b.png">

The podfile used:

```
# Your Podfile should contain the following:
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/goinstant/pods-specs-public'
pod 'SOS', '1.2.3', :inhibit_warnings => true

post_install do |installer_representation|
  installer_representation.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
    end
  end
end

```

I've tested this on the example app and another app I'm working on with the same results, let me know if you need further information or I'm doing something wrong.

Thanks in advance 👏

**Comment by adamwdennis** [comment]
Hi @JaviLorbada,

Thank you for reporting this issue.

The current version of Xcode tries to generate dSYM files for debug builds, which are unnecessary.

We will fix this in a subsequent release, but for now you can fix this by opening the project in Xcode, and going to Build Settings -> Build Options -> Debug Information Format... change this value from `DWARF with dSYM File` to `DWARF`.

Cheers.
